// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyulzzOfNVQPmsW7H6qs0UD2HqPWbrCNs',
    appId: '1:242169539324:web:6917d8c7edca8da2158579',
    messagingSenderId: '242169539324',
    projectId: 'app-expenso-tracker',
    authDomain: 'app-expenso-tracker.firebaseapp.com',
    storageBucket: 'app-expenso-tracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQr_EwUR-tQ5xavZtHljoCALOnNOcLrgM',
    appId: '1:242169539324:android:b8c04e6128e2710a158579',
    messagingSenderId: '242169539324',
    projectId: 'app-expenso-tracker',
    storageBucket: 'app-expenso-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7BKsQWTNv822Hs9IDOtz_IrYWgviARiA',
    appId: '1:242169539324:ios:f45dff3828c93de1158579',
    messagingSenderId: '242169539324',
    projectId: 'app-expenso-tracker',
    storageBucket: 'app-expenso-tracker.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7BKsQWTNv822Hs9IDOtz_IrYWgviARiA',
    appId: '1:242169539324:ios:f45dff3828c93de1158579',
    messagingSenderId: '242169539324',
    projectId: 'app-expenso-tracker',
    storageBucket: 'app-expenso-tracker.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyulzzOfNVQPmsW7H6qs0UD2HqPWbrCNs',
    appId: '1:242169539324:web:4f6385855366bccf158579',
    messagingSenderId: '242169539324',
    projectId: 'app-expenso-tracker',
    authDomain: 'app-expenso-tracker.firebaseapp.com',
    storageBucket: 'app-expenso-tracker.firebasestorage.app',
  );
}
